export const AUTH_PATTERNS = {
  SIGNUP: 'auth.signup',
  LOGIN: 'auth.login',
  REFRESH_TOKEN: 'auth.refresh_token',
  VERIFY_TOKEN: 'auth.verify_token',
  LOGOUT: 'auth.logout',
  GET_USER: 'auth.get_user',
  LIST_USERS: 'auth.list_users',
  UPDATE_USER: 'auth.update_user',
  DELETE_USER: 'auth.delete_user',
};

export const QUESTION_PATTERNS = {
  CREATE: 'question.create',
  FIND_ALL: 'question.find_all',
  FIND_ONE: 'question.find_one',
  UPDATE: 'question.update',
  PUBLISH: 'question.publish',
  SAVE_DRAFT: 'question.save_draft',
  ARCHIVE: 'question.archive',
  DUPLICATE: 'question.duplicate',
  BULK_TAG: 'question.bulk_tag',
  EXPORT_CSV: 'question.export_csv',
  IMPORT: 'question.import',
  GET_HISTORY: 'question.get_history',
  RESTORE_VERSION: 'question.restore_version',
  FLAG_REVIEW: 'question.flag_review',
  CLEAR_FLAG: 'question.clear_flag',
};

export const EXAM_PATTERNS = {
  PAPER_CREATE: 'exam.paper.create',
  PAPER_FIND_ALL: 'exam.paper.find_all',
  PAPER_FIND_ONE: 'exam.paper.find_one',
  PAPER_UPDATE: 'exam.paper.update',
  PAPER_PUBLISH: 'exam.paper.publish',
  PAPER_DELETE: 'exam.paper.delete',
  SCHEDULE_CREATE: 'exam.schedule.create',
  SCHEDULE_FIND_ALL: 'exam.schedule.find_all',
  SCHEDULE_FIND_ONE: 'exam.schedule.find_one',
  SCHEDULE_UPDATE: 'exam.schedule.update',
  SCHEDULE_COMPLETE: 'exam.schedule.complete',
  SCHEDULE_CANCEL: 'exam.schedule.cancel',
  STUDENT_EXAMS: 'exam.student.exams',
  STUDENT_PAPER: 'exam.student.paper',
  ATTEMPT_START: 'exam.attempt.start',
  ATTEMPT_SAVE: 'exam.attempt.save',
  ATTEMPT_SUBMIT: 'exam.attempt.submit',
  ATTEMPT_GET: 'exam.attempt.get',
  ATTEMPT_LIST: 'exam.attempt.list',
};

export const MONITOR_PATTERNS = {
  UPSERT_SESSION: 'monitor.upsert_session',
  GET_SESSIONS: 'monitor.get_sessions',
  UPDATE_STATUS: 'monitor.update_status',
  UPDATE_PROGRESS: 'monitor.update_progress',
  LOG_VIOLATION: 'monitor.log_violation',
  GET_VIOLATIONS: 'monitor.get_violations',
  GET_CANDIDATE_VIOLATIONS: 'monitor.get_candidate_violations',
  EXTEND_TIME: 'monitor.extend_time',
  TERMINATE: 'monitor.terminate',
  LOG_WARNING: 'monitor.log_warning',
};

export const WS_EVENTS = {
  SESSION_UPDATE: 'session.update',
  VIOLATION: 'violation',
  VIOLATION_EVENT: 'violation.event',
  WARNING: 'warning',
  WARNING_RECEIVED: 'warning.received',
  TERMINATED: 'terminated',
  TERMINATE: 'terminate',
  EXAM_TERMINATED: 'exam.terminated',
  TIME_EXTENDED: 'time.extended',
  EXTEND_TIME: 'extend.time',
  CANDIDATE_UPDATE: 'candidate.update',
  CANDIDATE_JOIN: 'candidate.join',
  CANDIDATE_LEAVE: 'candidate.leave',
  CANDIDATE_FRAME: 'candidate.frame',
  CANDIDATE_PROGRESS: 'candidate.progress',
  PROCTOR_JOIN: 'proctor.join',
  SESSION_LIST: 'session.list',
  SEND_MESSAGE: 'send.message',
  SEND_WARNING: 'send.warning',
  MESSAGE_RECEIVED: 'message.received',
  FRAME_UPDATE: 'frame.update',
  BROADCAST: 'broadcast',
};
